apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xusers.keycloak.platformref.upbound.io
spec:
  compositeTypeRef:
    apiVersion: keycloak.platformref.upbound.io/v1alpha1
    kind: XUser
  writeConnectionSecretsToNamespace: upbound-system
  resources:
    - name: user
      base:
        apiVersion: user.keycloak.crossplane.io/v1alpha1
        kind: User
        spec:
          forProvider:
            realmId: master
            enabled: true
            emailVerified: true
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: spec.parameters.username
          toFieldPath: spec.forProvider.username
        - fromFieldPath: spec.parameters.firstname
          toFieldPath: spec.forProvider.firstName
        - fromFieldPath: spec.parameters.lastname
          toFieldPath: spec.forProvider.lastName
        - fromFieldPath: spec.parameters.initialPassword
          toFieldPath: spec.forProvider.initialPassword
        - fromFieldPath: spec.parameters.email
          toFieldPath: spec.forProvider.email

    - name: groupassignment
      base:
        apiVersion: user.keycloak.crossplane.io/v1alpha1
        kind: Groups
        spec:
          forProvider:
            realmId: master
            userIdSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: spec.parameters.group
          toFieldPath: spec.forProvider.groupIdsSelector.matchLabels.type
