apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcnoe.aws.platformref.upbound.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: aws.platformref.upbound.io
  names:
    kind: XCNOE
    plural: xcnoe
  claimNames:
    kind: CNOE
    plural: cnoe
  connectionSecretKeys:
    - kubeconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Cluster configuration parameters.
                  properties:
                    id:
                      type: string
                      description: ID of this Cluster that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    iam:
                      type: object
                      description: IAM configuration to connect as ClusterAdmin.
                      properties:
                        roleArn:
                          description: The IAM Role ARN to connect as ClusterAdmin.
                          type: string
                        userArn:
                          description: The IAM User ARN to connect as ClusterAdmin.
                          type: string
                    networkSelector:
                      type: string
                      description: NetworkSelector employs a specific type of network architecture.
                      enum:
                        - basic
                      default: basic
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    route53zoneId:
                      description: route53zoneId specifies the Route53 Zone ID to use for DNS records.
                      type: string
                    version:
                      type: string
                      description: Kubernetes version of the Cluster
                      enum:
                        - "1.28"
                        - "1.27"
                        - "1.26"
                      default: "1.27"
                    nodes:
                      type: object
                      description: Cluster node configuration parameters.
                      properties:
                        count:
                          type: integer
                          description: Desired node count, from 1 to 100.
                        instanceType:
                          type: string
                          description: instance types associated with the Node Group.
                          default: t3.small
                      required:
                        - count
                        - instanceType
                    operators:
                      description: Configuration for operators.
                      type: object
                      default:
                        argocd:
                          version: "5.51.1"
                        prometheus:
                          version: "52.1.0"
                      properties:
                        argocd:
                          description: Configuration for the ArgoCD GitOps operator.
                          type: object
                          properties:
                            version:
                              description: flux helm-chart version to run.
                              type: string
                              default: "5.51.1"
                          required:
                            - version
                        prometheus:
                          description: Configuration for the Prometheus Helm-Chart.
                          type: object
                          properties:
                            version:
                              description: prometheus helm-chart version to run.
                              type: string
                              default: "52.1.0"
                          required:
                            - version
                    gitops:
                      description: GitOps configure gitops system
                      type: object
                      properties:
                        git:
                          type: object
                          properties:
                            url:
                              description: URL specifies the Git repository URL, it can be an HTTP/S
                                or SSH address.
                              pattern: ^(http|https|ssh)://.*$
                              type: string
                            path:
                              type: string
                              default: "/"
                            ref:
                              description: Reference specifies the Git reference to resolve and
                                monitor for changes.
                              type: object
                              properties:
                                name:
                                  description: "Name of the reference to check out"
                                  type: string
                          required:
                            - url
                            - ref
                      required:
                        - git
                  required:
                    - deletionPolicy
                    - gitops
                    - id
                    - nodes
                    - operators
                    - providerConfigName
                    - region
                    - route53zoneId
              required:
                - parameters
            status:
              type: object
              properties:
                subnetIds:
                  type: array
                  items:
                    type: string
                cnoe:
                  description: Freeform field containing status information for cnoe
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
